modLoader="javafml"
loaderVersion="[34,)" #forge version dep
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/iChun/Torched/issues"

[[mods]]
    modId="torched"
    version="${file.jarVersion}" #mandatory
    displayName="Torched"
    displayURL="https://ichun.me/mods/torched/"
    authors="iChun"
    description='''
    Adds a couple of items which aids with torch placement. Mainly a gun, rocket, and launcher.
    '''

[[dependencies.torched]]
    modId="ichunutil"
    mandatory=true
    versionRange="[10.0.0,11)"
    ordering="NONE"
    side="BOTH"
